[workspace]
members = [
    "exercises/0-intro",
    "exercises/A1/1-basic-syntax",
    "exercises/A1/2-move-semantics/",
    "exercises/A2/0-borrowing",
    "exercises/A2/1-error-propagating",
    "exercises/A2/2-slices",
    "exercises/A2/3-error-handling",
    "exercises/A2/4-boxed-data",
    "exercises/A2/5-bonus-ring-buffer",
    "exercises/A3/2-local-storage-vec/",
    "exercises/B/1-my-serde-app",
    "exercises/B/3-fizzbuzz",
    "exercises/C1-tf-idf",
    "exercises/C2-mutex",
    "slides/examples/B-application-programming",
]
